### ISSUE TITLE
Quiver for diploid genome?

### ISSUE THREAD

**Issue by danshu** [PacificBiosciences/GenomicConsensus#101]
Hi,

I intend to polish my diploid assembly using quiver. However, it was mentioned here (https://github.com/PacificBiosciences/GenomicConsensus/blob/master/doc/FAQ.rst) that "the behavior of on sample mixtures or diploid/polyploid samples is undefined". So should I still try quiver?

Best,
Quan

**Comment by dalexander** [comment]
There is an experimental `--diploid` flag but it's not reliable and I don't recommend using it.  I think the better bet is just to use the default options.
