### ISSUE TITLE
No local packages or download links found for ConsensusCore>=1.0.1

### ISSUE THREAD

**Issue by mictadlo** [PacificBiosciences/GenomicConsensus#103]
Hi,
I ran `python setup.py install` and I got this error:

	Installed /usr/local/lib/python2.7/dist-packages/GenomicConsensus-2.1.0-py2.7.egg
	Processing dependencies for GenomicConsensus==2.1.0
	Searching for ConsensusCore>=1.0.1
	Reading https://pypi.python.org/simple/ConsensusCore/
	Couldn't find index page for 'ConsensusCore' (maybe misspelled?)
	Scanning index of all packages (this may take a while)
	Reading https://pypi.python.org/simple/
	No local packages or download links found for ConsensusCore>=1.0.1
	error: Could not find suitable distribution for Requirement.parse('ConsensusCore>=1.0.1')

Did I miss anything?

Thank you in advance.

Mic

**Comment by afif-elghraoui** [comment]
See https://github.com/PacificBiosciences/ConsensusCore

**Comment by dalexander** [comment]
Right, it's not on PyPI
