### ISSUE TITLE
Problem running variantCaller

### ISSUE THREAD

**Issue by pb-cdunn** [PacificBiosciences/GenomicConsensus#104]
I thought I might be out-of-date, so I've completely rebuilt my pitchfork. I still see this error:
```python
INFO:falcon_polish.sys:system('variantCaller --log-level DEBUG --algorithm arrow --minConfidence 40 --minCoverage 5 --alignmentSetRefWindows --referenceFilename /home/UNIXHOME/cdunn/repo/pb/smrtanalysis-client/smrtanalysis/siv/testkit-jobs/sa3_pipelines/hgap5_fake/synth5k/job_output/tasks/falcon_ns.tasks.task_hgap_run-0/run-fasta2referenceset/asm.referenceset.xml -o consensus.fastq -o variants.gff -o consensus.fasta /home/UNIXHOME/cdunn/repo/pb/smrtanalysis-client/smrtanalysis/siv/testkit-jobs/sa3_pipelines/hgap5_fake/synth5k/job_output/tasks/falcon_ns.tasks.task_hgap_run-0/run-gc_scatter/chunk_alignmentset_0.alignmentset.xml')
Process ArrowWorkerProcess-1:
Traceback (most recent call last):
  File "/opt/python-2.7.9/lib/python2.7/multiprocessing/process.py", line 258, in _bootstrap
    self.run()
  File "/home/UNIXHOME/cdunn/repo/pb/pf/smrtanalysis/bioinformatics/ext-vc/pivc/GenomicConsensus/GenomicConsensus/Worker.py", line 96, in run
    self._run()
  File "/home/UNIXHOME/cdunn/repo/pb/pf/smrtanalysis/bioinformatics/ext-vc/pivc/GenomicConsensus/GenomicConsensus/Worker.py", line 77, in _run
    result = self.onChunk(datum)
  File "/home/UNIXHOME/cdunn/repo/pb/pf/smrtanalysis/bioinformatics/ext-vc/pivc/GenomicConsensus/GenomicConsensus/arrow/arrow.py", line 205, in onChunk
    refContig, options.coverage, self.arrowConfig)
  File "/home/UNIXHOME/cdunn/repo/pb/pf/smrtanalysis/bioinformatics/ext-vc/pivc/GenomicConsensus/GenomicConsensus/arrow/arrow.py", line 118, in consensusAndVariantsForWindow
    arrowConfig)
  File "/home/UNIXHOME/cdunn/repo/pb/pf/smrtanalysis/bioinformatics/ext-vc/pivc/GenomicConsensus/GenomicConsensus/arrow/utils.py", line 361, in consensusForAlignments
    mappedReads = [ arrowConfig.extractMappedRead(aln, refStart) for aln in alns ]
  File "/home/UNIXHOME/cdunn/repo/pb/pf/smrtanalysis/bioinformatics/ext-vc/pivc/GenomicConsensus/GenomicConsensus/arrow/model.py", line 104, in extractMappedRead
    strand = cc.StrandType_REVERSE if aln.isReverseStrand else cc.StrandType_FORWARD
AttributeError: 'module' object has no attribute 'StrandType_REVERSE'
```
This used to work for me. It still works for the same code built internally (i.e. the "tarball", via the Jenkins build, which then runs as smrtlink). So I guess I have a problem with how this is built via pitchfork. Any ideas?

**Comment by armintoepfer** [comment]
@nlhepler @mhsieh we should use unanimity in pitchfork

**Comment by dalexander** [comment]
investigating...

to your comment @armintoepfer: once we get unanimity plumbed into the main build, we will delete the legacy repos to help flush out such issues

**Comment by dalexander** [comment]
@pb-cdunn not sure what's going on here Chris but I think this is a problem on your end, my guess is that you have some stale version of ConsensusCore2 installed?


```
In [1]: import ConsensusCore2

In [2]: ConsensusCore2.StrandType_REVERSE
Out[2]: 1
```

**Comment by dalexander** [comment]
Reopen if you can confirm this is an issue on our enmd.

**Comment by dalexander** [comment]
Chris, if pitchfork is somehow installing a stale version of CC2, could you file an issue on pitchfork?

**Comment by pb-cdunn** [comment]
@dalexander, yes already filed in pitchfork, based on Armin's private message (re: Unanimity). (See link above.) This ticket is fine _closed_.

The main thing is that we are in August, so I wanted to get this into a Sprint if possible and had no idea how.

**Comment by pb-cdunn** [comment]
Folks, I am completely dead in the water. Could someone work with me privately until this is resolved?

**Comment by natechols** [comment]
It might be easier and faster to just symlink to the official build's variantCaller in ~/bin - that's what I've been doing instead of fighting C++ errors.

**Comment by pb-cdunn** [comment]
Ok. Thx, Nat. Trying that ...

**Comment by pb-cdunn** [comment]
Lance is helping privately. Closing this.

**Comment by pb-cdunn** [comment]
Nat's idea worked. Thx.

**Comment by dalexander** [comment]
Lance pointed out that the API change only made it into unanimity, not CC2, so that explains what's going on.

**Comment by mhsieh** [comment]
Works for me
```
login:~$ bash --init-file /opt/pfbuild_FC/setup-env.sh 
bash-4.2$ python << EOF
> import ConsensusCore2
> print ConsensusCore2.StrandType_REVERSE
> EOF
1
bash-4.2$ 
```
I think you might need a cleaning in the `DEVOPT=-e` mode, that is, removing the _build and _pitchforktmp folder from the project folder of ConsensusCore2.

**Comment by mhsieh** [comment]
Meanwhile I will probably wait for the some updates from unanimity project tomorrow.

**Comment by mhsieh** [comment]
by the way unanimity port is done in pitchfork

**Comment by nlhepler** [comment]
++mhsieh
