### ISSUE TITLE
Failure: unrecognized algorithm arrow

### ISSUE THREAD

**Issue by linz-li** [PacificBiosciences/GenomicConsensus#107]
when I use the command "quiver -j8 --referenceFilename ./Ref.fasta --algorithm=arrow -o quiver.fa input.fofn " , I got a error:

Failure: unrecognized algorithm arrow

why?

**Comment by linz-li** [comment]
and when I replace the  --algorithm=arrow to --algorithm=quiver   or --algorithm=plurality there is nothing wrong.

**Comment by dalexander** [comment]
The correct usage is `variantCaller --algorithm={arrow,quiver,plurality}`. 

But I think you are using an old version of GenomicConsensus, perhaps as installed in SMRTanalysis 2.3 or lower.  Arrow is not available there.
