### ISSUE TITLE
Expected running time of Quiver

### ISSUE THREAD

**Issue by JohnUrban** [PacificBiosciences/GenomicConsensus#111]
Hello,

Thanks for the great tools.

I am just curious about what to expect in terms of the resources (including memory and time) needed by Quiver.

I am running it right now with ~16Gbp of PacBio reads (something like 54x coverage) for a ~300 Mb genome. It is running with 8 threads, 32GB RAM, and I allotted it 48 hours. I am wondering if you have any prediction as to whether it will finish before the 48 hours is up.

best,

  John

**Comment by dalexander** [comment]
I don't have such numbers handy, but if you use the verbose flag `-v` or `-vv` you will see progress messages, which you could use to estimate the total runtime.
