### ISSUE TITLE
pipe in consensus contig names offering analysis hang ups

### ISSUE THREAD

**Issue by afinit** [PacificBiosciences/GenomicConsensus#112]
The `|` character in the names of the consensus contigs offers problems in post consensus analyses. Some programs can't handle this character in contig names, and any work done on the command line with these names needs to be careful. I propose that this character be changed to something a little more innocuous such as an underscore.

As a frequent user of PacBio software, this would simplify downstream analyses so that I don't have to sub out those characters or create work arounds.

**Comment by dalexander** [comment]
Thanks for the suggestion, I will consider the underscore
