### ISSUE TITLE
Quiver reports fewer output sequences than input sequences.

### ISSUE THREAD

**Issue by JohnUrban** [PacificBiosciences/GenomicConsensus#113]
Hi,

I essentially follow these instructions:
https://github.com/PacificBiosciences/pbalign/wiki/Tutorial:-How-to-divide-and-conquer-large-datasets-using-pbalign

The command I use for quiver thereafter is:

```
quiver -j${THREADS} ${INPUT} -r ${REF} -o $OUTGFF -o $OUTFASTQ -o $OUTFASTA
```

I have been seeing that the number of output sequences is less than the number of input sequences. Could you tell me a little bit about why that might be? Note that default for "--noEvidenceConsensusCall" says it should be 'lowercasereference'....

It seems like -- at least in the case I checked -- that contigs with 0 alignments and therefore not represented in the cmp.h5 file are not in the final quiver output. However, Quiver is also given the reference that has all the sequences. Ideally it should use the reference to make sure it processes all contigs -- not just the subset of contigs represented in the alignments.

Any information you could give me about this would be appreciated.

I guess for now I need to go through and figure out which contigs were left out and add them back....

best,

  John Urban

**Comment by dalexander** [comment]
I think your guess is correct.  I think the top loop in the program iterates over only those contigs with mappings.  I can look into trying to fix this, as I agree with you that it's probably not the right default.

**Comment by dalexander** [comment]
Copying this into internal bug db
