### ISSUE TITLE
Can quiver input use fasta/fastq instead of h5

### ISSUE THREAD

**Issue by lijingjing1** [PacificBiosciences/GenomicConsensus#118]
Hi all

    Can i use subreads fasta or fastq to instead of h5 files to quiver with bwa/blasr?

Just give up the reads QV information and in sequel subreads.bam it also have no QV information.

I also find in falcon unzip a step in quiver just use fasta to generate bam file with pbalign for variantCaller.

**Comment by dalexander** [comment]
No, you need the "rich" QV information present in the hdf5 file.

**Comment by lijingjing1** [comment]
Thank you reply ,but in falcon unzip step 4 it just use subreads fasta to finish quiver and also in sequel data it have no QV information in subreads.bam files.
