### ISSUE TITLE
Running Quiver from several bam files

### ISSUE THREAD

**Issue by a-velt** [PacificBiosciences/GenomicConsensus#119]
Dear developers,

I don't know if I write in the right place, but I have a question about the use of Quiver.

I have a pacbio run with a lot of bax.h5 files, three bax.h5 per movie, of type "${ID}.1.bax.h5 ${ID}.2.bax.h5 ${ID}.3.bax.h5". From these files, I generated one bam file per movie with the command : 
> bash --init-file /cm/shared/apps/pitchfork/setup-env.sh
bax2bam -o /bax2bam/${ID}.bam /home/avelt/Archives/PacBio/GW/bax.h5/${ID}\*bax\*

So from three bax files, I obtained one bam file. Then, I aligned these bam files against my primary contigs, which are my reference (generated with Falcon), like that : 
> source /cm/shared/apps/pitchfork/setup-env.sh
pbalign --nproc 4 --tmpDir mytmpdir/ /bax2bam/${ID}.bam p_ctg.ref.fa /aligned_bam/${ID}.aligned.bam

So now, I have a lot of aligned bam files, and I want to polish my assembly (my p_ctg.ref.fa) with Quiver.

If I type quiver --help, I have : 
> Basic required options:
  inputFilename         The input cmp.h5 file
  --referenceFilename REFERENCEFILENAME, --reference REFERENCEFILENAME, -r REFERENCEFILENAME
                        The filename of the reference FASTA file (default:
                        None)
  -o OUTPUTFILENAMES, --outputFilename OUTPUTFILENAMES
                        The output filename(s), as a comma-separated
                        list.Valid output formats are .fa/.fasta, .fq/.fastq,
                        .gff (default: [])

So, ok, I have the reference and the outputfilenames, but I don't have one cmp.h5 file but several bam files. My question is, how to run quiver with several bam files ? Do I have to merge all of my bam files in one bam ? If I well understood, the cmp.h5 format will be deprecated soon, so I followed the Pacbio's instructions to generated the bam files, but now, I'm blocked with the use of Quiver ... If I well understand, I can't create a .fofn file containing all my bam files and I don't know if a merge of all my files is a good choice. Any help would be precious. Thank you.

Best,
Amandine

**Comment by dalexander** [comment]
If you are using quiver built from "pitchfork" (or otherwise built from latest github), then in fact it does accept bam files (maybe I need to update the help text), and it does accept a "FOFN" where you just list all the individual BAM files, one per line.  Can you try that

**Comment by a-velt** [comment]
I have tested and it works fine with a .fofn file, sorry I don't have tested because I stopped on the help.

Thank you and have a nice week-end,
Amandine
