### ISSUE TITLE
Quiver (SMRT2.3.0) using too much RAM

### ISSUE THREAD

**Issue by ambarrio** [PacificBiosciences/GenomicConsensus#120]
Hi,

I am using SMRT2.3.0 to quiver a draft assembly because we aligned PB reads with BLASR. I tested two machines, the first one with 512GB and the second with 1Tb RAM. The issue is that if I use the many processor mode, it crashes at some point - in the first machine ~128 contigs and in the second ~192 contigs.

First, I wondered if it was the number of processes so I halved them so they'd have more memory available. But the crash it is delayed by no much.

Then I wondered if it was an error on a particular contig, now I want to make the program go by all of the contigs so at least I might get some of them corrected.

My question is how the memory footprint of the program works. Does it grow so much because you store the places were deletions and insertions occur during the run so you learn from them? Or does it get rebooted every time new contigs are seen? If I run contigs sequentially one after the other will be my corrections somewhat worse?

Do you recommend running arrow instead? Is the HMM memory footprint different?

Thanks,
álvaro

**Comment by dalexander** [comment]
Thanks for reporting this.  

In general the memory footprint should be mostly constant except for variant objects, which I do believe are retained in a growing list in memory before flushing to disk at termination.  We could definitely improve on this, for scenarios with massive variant lists.  

*However*, if you are attempting to run your analysis as a single Quiver job on a large SMP, I suggest you would be better off following these instructions to split your job on a cluster: https://github.com/PacificBiosciences/GenomicConsensus/blob/master/doc/HowTo.rst#running-a-large-scale-resequencingpolishing-job-in-smrtanalysis-23

Quiver and Arrow should perform similarly in this regard, there's no great advantage in switching.
