### ISSUE TITLE
Can I output the corresponding subread names for strand css?

### ISSUE THREAD

**Issue by yech1990** [PacificBiosciences/GenomicConsensus#125]
Sorry for writing an issue here.

I run `ccs` with option `--byStrand`. I can get both ccs_fwd and ccs_rev read for each zmw read.

But I want to know which subread in the subread.bam file is use to infer ccs read in ccs.bam.

Can I output the subread name is the log file?

BTW, I notice that `ccs` doesn't do location checking for each subread. I had tried changing the qs and qe tag to any random integer, but the result is not affected. How can `ccs` know the subread strand orientation without the information of read location span?

@armintoepfer 

https://github.com/PacificBiosciences/unanimity

**Comment by armintoepfer** [comment]
You do not get the orientation information as a result. Align your reads against the output to find out which subreads got used for which strand.
