### ISSUE TITLE
Large cmp.h5 file

### ISSUE THREAD

**Issue by ascendo** [PacificBiosciences/GenomicConsensus#13]
Hi!

My name is Won and I am a postdoc in UNR.

I try to use Quiver for polishing step.

I have 61G cmp.h5 and 371M reference with 1173 contigs.

If I use 5G cmp.h5 it works well but with this large amount of cmp.h5 file, all process goes to sleep.

Regards,

Won

Here is my command:

variantCaller.py -P /home/wyim/scratch/smrtpipe/pbsmrtpipe/current/analysis/etc/algorithm_parameters/2014-03 -v --debug -j 16 --algorithm=quiver polish/aligned_reads.cmp.h5 -r polish/reference/sequence/reference.fasta -o polish/corrections.gff -o polish/polished_assembly.fasta -o polish/polished_assembly.fastq.gz

**Comment by madhubioinfo** [comment]
hello @pb-jlandolin i have installed 2.3 actually installation worked well, then i have ran a test data set it ran well, now if i run my original data its give this error please help me in solving this
Traceback (most recent call last):
  File "/usr/ajeyadata/install/smrtanalysis_2.3.0.140936/analysis/bin/smrtpipe.py", line 11, in <module>
    from SMRTpipe.SmrtPipeMain import SmrtPipeMain, _sanityCheck
ImportError: No module named SMRTpipe.SmrtPipeMain

**Comment by dalexander** [comment]
@madhubioinfo your issue has nothing to do with GenomicConsensus, please follow up with technical support
