### ISSUE TITLE
pysam version issue

### ISSUE THREAD

**Issue by gouthamatla** [PacificBiosciences/GenomicConsensus#15]
I have installed both pysam versions 0.8.0 and 0.8.1, but still it shows the following error:

```sh
error: Installed distribution pysam 0.8.0 conflicts with requirement pysam==0.8.1
```
It is also wired that it looks for pysam 0.8.0 and complains about 0.8.1

```sh
Processing dependencies for GenomicConsensus==0.9.1
Searching for pysam==0.8.0
```

**Comment by dalexander** [comment]
Uninstall pysam-0.8.0
