### ISSUE TITLE
Quiver memory consumption 

### ISSUE THREAD

**Issue by chklopp** [PacificBiosciences/GenomicConsensus#16]
I'm running Quiver on a 400Mb assembled genome with 71X converage. It has already used 500Gb of RAM and is still running. It seem to load the complete sam file in memory. 
Is there a way to avoid this?

**Comment by dalexander** [comment]
Are you running a single quiver job?  For large genomes it is really intended that you split up the processing into multiple cluster submissions (split by contig).

That said, this sounds like a memory leak...  can you please share the output of ``quiver --version``?

**Comment by chklopp** [comment]
(smrtanalysis-2.3.0)  ~ $ /save/smrtanalysis/current/analysis/bin/quiver --version
   GenomicConsensus version: 0.9.2
  ConsensusCore version: 0.8.8
  h5py version: 2.2.0
  hdf5 version: 1.8.12

**Comment by chklopp** [comment]
I run quiver from SMRT pipe. Is there an example XML file including the genome splitting part?

**Comment by dalexander** [comment]
@PacificBiosciences/techsupport

**Comment by dalexander** [comment]
please contact tech support if they haven't reached out to you already

**Comment by jkaralius** [comment]
Hi @chklopp 

To quiver large assemblies, you can use SMRT Analysis BAM_Resequncing_Beta.1 protocol.  The following thread on SeqAnswers discusses this approach.

http://seqanswers.com/forums/showthread.php?t=58129

The alternate method proposed entails splitting the genome manually, covered in the pbalign wiki:

https://github.com/PacificBiosciences/pbalign/wiki/Tutorial:-How-to-divide-and-conquer-large-datasets-using-pbalign
