### ISSUE TITLE
Running GenomicConsensus.Quiver.utils.consensusForAlignments() with multiprocessing generates all kinds of errors

### ISSUE THREAD

**Issue by verheytb** [PacificBiosciences/GenomicConsensus#17]
I have written some Python code that basically calls on the consensusForAlignments() function from GenomicConsensus.Quiver.utils. I need to use this function a lot, so I'm trying to use multiprocessing.Pool to speed things up.

When I call this function only once at a time, it returns as expected; However, when I call it from multiple worker processes using multiprocessing.Pool, I get a variety of errors including "IOError: can't read data (Dataset: Read failed)", "RuntimeError: Invalid DelTag field---must be ASCII encoded.", and "KeyError: unable to open object (Symbol table: Can't open object)".

I thought that Python's multiprocessing has each worker function in separate memory space, so there shouldn't be any memory conflicts or the like that would cause something like that.

Any ideas?

**Comment by dalexander** [comment]
That's the way it *should* work, but we historically have run into problems when using hdf5 in mutli-process operation.  IIRC, you need to make sure you don't have the hdf5 file open in the parent process before you fork any child processes.

**Comment by verheytb** [comment]
Okay, that was the problem. I've rewritten it to open the file separately for each process, and that is working flawlessly.

**Comment by dalexander** [comment]
yes... that's basically what quiver does.
