### ISSUE TITLE
How to run quiver on BWA-generated alignment?

### ISSUE THREAD

**Issue by yunfeiguo** [PacificBiosciences/GenomicConsensus#20]
Dear Quiver developers,

I wonder how to run quiver on bwa results? It seems quiver requires 3.0b7 version of pacbio BAM format. Since pacbio format is compatible with standard BAM format, is there a way to make quiver work with BWA? Thanks!

**Comment by yunfeiguo** [comment]
```
$ quiver --version
  GenomicConsensus version: 1.1.0
  ConsensusCore version: 1.0.1
  h5py version: 2.5.0
  hdf5 version: 1.8.15
```

**Comment by dalexander** [comment]
If you can get the BAM to adhere to our specification, then it will work.  But since BWA is a third party tool, we can't offer support. 

http://pacbiofileformats.readthedocs.org/en/3.0/BAM.html
