### ISSUE TITLE
Running quiver on selected subreads only

### ISSUE THREAD

**Issue by arangrhie** [PacificBiosciences/GenomicConsensus#22]
Hi,

We need to run quiver only on selected subreads from different set of SMRT cells.
However, the problem is, that we need to use all the .h5 files containing the subreads.
This is extremely time and memory consuming.
Is there a way to run quiver only over selected subreads?
The selected subreads are made in fasta and in.fofn file, containing only selected fasta sequences with the same .fasta name, but different directory.

**Comment by ebioman** [comment]
I would second that. We have a sample which contained as well some problematic reads which we filtered out systematically. Using again all reads and re-introducing this error-prone reads is troublesome for us.
It further increases the mapping time by the factor 3 for us.

**Comment by dalexander** [comment]
Your best bet is to use pbh5tools to filter the cmp.h5 (or bas.h5) file according to criteria that you specify.

 https://github.com/PacificBiosciences/pbh5tools/blob/master/doc/index.rst
