### ISSUE TITLE
Failure: Selected Quiver parameter set is incompatible with this cmp.h5 file due to missing data tracks

### ISSUE THREAD

**Issue by orangeSi** [PacificBiosciences/GenomicConsensus#25]
Hi~
   I use samtoh5(that is from blasr ) to convert sam file(generated by daligner) to cmp.h5. 
   Then I use quiver with that cmp.h5 ,but an error is happen:
             "Failure: Selected Quiver parameter set is incompatible with this cmp.h5 file due to missing data tracks."

Thanks!

**Comment by dalexander** [comment]
The problem is not in GenomicConsensus, it's that you're not preparing your cmp.h5 correctly.  Tech support can help.  

@PacificBiosciences/techsupport

**Comment by dalexander** [comment]
please contact tech support if they haven't reached out to you
