### ISSUE TITLE
Not an issue, but rather a question/request 

### ISSUE THREAD

**Issue by mahulchak** [PacificBiosciences/GenomicConsensus#28]
Does quiver beeak contigs if there is no read coverage for a region? In other words, if there are no read coverage for a small region, that would indicate that two contigs have been misassembled at that region and should be broken up. If quiver could do something like that, that would be pretty awesome. Or, does it already do that?

**Comment by pb-jlandolin** [comment]
No, quiver does not do that.  You're thinking of the error correction step, that may break long reads if there is not enough short(er) read coverage.
