### ISSUE TITLE
ChemistryLookupError: Chemistry information could not be found in cmp.h5!

### ISSUE THREAD

**Issue by sudhirjadhao** [PacificBiosciences/GenomicConsensus#30]
Command used:
pbalign --nproc 50 --forQuiver --tmpDir TMPDIR all_bax_h5.fofn p_ctg.fa p_ctg_5cov.cmp.h5

cmph5tools.py sort out_all.cmp.h5

pbalign version:0.2.0.141024

while running quiver its showing error  "ChemistryLookupError: Chemistry information could not be found in cmp.h5!"
Can you please tell me where I am going wrong

**Comment by dalexander** [comment]
This is a good question for @PacificBiosciences/techsupport

**Comment by MichelMoser** [comment]
had the same problem. 
can be easily solved with loadChemistry.py

**Comment by pb-jlandolin** [comment]
Yes, you need to run loadChemistry.py first.  

You should have SMRT Analysis installed before attempting to run on the command-line. Look in the `/opt/smrtanalysis/userdata/jobs/{jobid_prefix}/{jobid}/workflow' directory of a "ReSequencing" job to find exact command to execute.

**Comment by sudhirjadhao** [comment]
Many thanks for the comment..
Can you pleas tell me brief about load chemistry..  how command works..
I am not able to get manual of loadChemistry.py

**Comment by MichelMoser** [comment]
```
(pacbio_env)[mmoser]$ loadChemistry.py -h

loadChemistry.py

 Load chemistry info into a cmp.h5, just copying the triple.  Note
 that there is no attempt to "decode" chemistry barcodes here---this
 is a dumb pipe.

 usage:
  % loadChemistry [input.fofn | list of input.ba[sx].h5] aligned_reads.cmp.h5

```
