### ISSUE TITLE
running quiver withouth consensusCore2

### ISSUE THREAD

**Issue by MichelMoser** [PacificBiosciences/GenomicConsensus#32]
Hi, 
I am worried to miss out on best consesus calling when not having ConsensusCore2 installed. 
When running quiver i get following message: 
````
[INFO] h5py version: 2.5.0
[INFO] hdf5 version: 1.8.5
[INFO] ConsensusCore version: 1.0.1
[INFO] ConsensusCore2 version: ConsensusCore2 unavailable
````
How critical is this message as it is only a INFO and not even a warning? 
Or is it just performance issue?

Also what is the most recent version of quiver? our administrator installed v2.0.0, hope thats recent

Thanks, 
Michel

**Comment by dalexander** [comment]
Ignore it.  But if you care about stability, run quiver from the SMRTanalysis bundle, not from github.
