### ISSUE TITLE
Quiver outputs empty files, quiverResult.vc.err does not report any errors

### ISSUE THREAD

**Issue by djwilki** [PacificBiosciences/GenomicConsensus#38]
Hello,

I am trying to run Quiver with the outputs of pbalign --forQuiver, but whenever I attempt to run Quiver, it outputs empty files and the quiverResult.vc.err file contains the following:

[INFO] h5py version: 2.2.0
[INFO] hdf5 version: 1.8.12
[INFO] ConsensusCore version: 0.7.6
[INFO] Starting.
[INFO] Peeking at CmpH5 file /home/lab/Desktop/clusteringConsensus-master/A01/hivalign.cmp.h5
[INFO] Input CmpH5 data: numAlnHits=81274
[INFO] Loading reference

Quiver isn't throwing any errors in the command window either.

Our input for Quiver is as follows:
variantCaller.py -vv -v  -j8 --algorithm=quiver /home/lab/Desktop/clusteringConsensus-master/A01/hivalign.cmp.h5 -r /home/lab/Desktop/clusteringConsensus-master/HIVemory.fasta -o /home/lab/Desktop/clusteringConsensus-master/A01/quiverResult.gff -o /home/lab/Desktop/clusteringConsensus-master/A01/quiverResult.consensus.fasta -o /home/lab/Desktop/clusteringConsensus-master/A01/quiverResult.consensus.fastq > /home/lab/Desktop/clusteringConsensus-master/A01/quiverResult.vc.out 2> /home/lab/Desktop/clusteringConsensus-master/A01/quiverResult.vc.err

Our cmp.h5 file preparation was as follows:

pbalign --forQuiver DATA.baxh5.fofn HIVemory.fasta hivalign.cmp.h5

with the fofn file containing our relevant bax.h5 files.

I'm just a little stumped at this point, as quiver isn't being very communicative about why it is not populating the outputs.

I'm just ending my day, so no rush on the reply.

Thank you,
DJWILKI

**Comment by dalexander** [comment]
Hi, this is a very old version of Quiver.  I recommend installing the latest version of SMRTanalysis 2.3 and trying again.
