### ISSUE TITLE
empty gff when using --referenceWindowsFile option

### ISSUE THREAD

**Issue by MichelMoser** [PacificBiosciences/GenomicConsensus#39]
Hi, 

When i run quiver on a subset of regions, it outputs me get a gff-file without any actual features. It contains only the headers of all the sequences of the reference file. Is that expected? 
The fasta and fastq files look ok and contain the sequences which are mentioned in test.01.rgn.

Quiver was run with: 
```
quiver --verbose -j32 merged.cmp.h5 --referenceFilename merged.fasta -o 2test.reg00.gff -o 2test.reg00.fasta -o 2test.reg00.fastq --referenceWindowsFile test.01.rgn -x 3 --fast 
```
commit: 388fec72c0e8cb4fbd5851d243b0b6d8da34ad7f

**Comment by dalexander** [comment]
If there are no variants found in the region, then this is the correct behavior.
