### ISSUE TITLE
KeyError: 'DS'

### ISSUE THREAD

**Issue by eltonjrv** [PacificBiosciences/GenomicConsensus#40]
Hello Quiver folks,

I am performing a separate PacBio assembly test with a software (Miniasm: https://github.com/lh3/miniasm). Since it has no error correction step, I need to generate a consensus with quiver on a downstream analysis in order to get more accurate contigs.
I am getting the following error running quiver independently within the smartanalysis virtualenv:
#################
(smrtanalysis-2.3.0) elton@fera:/work/schisto/elton/PacBio/miniasm/quiver-run$ nice quiver -j8 all-h5-merged.sorted.bam -r pacbio-corrected-hybrid-miniasm.fasta -o variants.gff -o pacbio-corrected-hybrid-miniasm-quiverCons.fasta 

[WARNING] 'fancyChunking' not yet available for BAM, disabling
Traceback (most recent call last):
  File "/work/schisto/elton/smrtanalysis/current/analysis/bin/variantCaller.py", line 5, in <module>
    sys.exit(main())
  File "/work/schisto/elton/smrtanalysis/current/redist/python2.7/lib/python2.7/site-packages/GenomicConsensus/main.py", line 367, in main
    return tr.main()
  File "/work/schisto/elton/smrtanalysis/current/redist/python2.7/lib/python2.7/site-packages/GenomicConsensus/main.py", line 278, in main
    with BamReader(options.inputFilename) as peekCmpH5:
  File "/work/schisto/elton/smrtanalysis/current/redist/python2.7/lib/python2.7/site-packages/GenomicConsensus/io/BamIO.py", line 100, in __init__
    self._loadReadGroupInfo()
  File "/work/schisto/elton/smrtanalysis/current/redist/python2.7/lib/python2.7/site-packages/GenomicConsensus/io/BamIO.py", line 58, in _loadReadGroupInfo
    ds = dict([pair.split("=") for pair in rg["DS"].split(";") if pair != ""])
KeyError: 'DS' 
#################

Could anyone shed some light on this issue?
Thanks in advance,
Elton
Note: I generated my h5*.sam files with blasr. In addition, I have used samtools in order to get .bam, sorted.bam and all-merged.sorted.bam files.

**Comment by dalexander** [comment]
This is doubtless not a BAM file that adheres to the PacBio BAM spec.

http://pacbiofileformats.readthedocs.org/en/3.0/BAM.html

**Comment by eltonjrv** [comment]
Thanks for the quick response, David!

And what would be the best tool (within the smrtanalysis virtualenv) to
generate a PacBio BAM?

Thanks again,
Best,
Elton



2016-01-11 16:46 GMT-02:00 David Alexander <notifications@github.com>:

> This is doubtless not a BAM file that adheres to the PacBio BAM spec.
>
> http://pacbiofileformats.readthedocs.org/en/3.0/BAM.html
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/PacificBiosciences/GenomicConsensus/issues/40#issuecomment-170649600>
> .
>



-- 
Elton J. R. Vasconcelos
DVM, PhD

**Comment by dalexander** [comment]
Sorry, there is no general tool to "fix up" a BAM file that doesn't follow our spec.  We ensure that the files we create with our own tools follow the spec.

**Comment by eltonjrv** [comment]
Ok, I see, David!

So, I'd better run through this recipe
https://github.com/PacificBiosciences/PacBioFileFormats/wiki/BAM-recipes in
order to get an aligned bam file that will fit properly for quiver, right?

Thanks for your attention,

Elton

2016-01-11 23:14 GMT-02:00 David Alexander <notifications@github.com>:

> Sorry, there is no general tool to "fix up" a BAM file that doesn't follow
> our spec. We ensure that the files we create with our own tools follow the
> spec.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/PacificBiosciences/GenomicConsensus/issues/40#issuecomment-170749170>
> .
>



-- 
Elton J. R. Vasconcelos
DVM, PhD

**Comment by dalexander** [comment]
Yes, that's right.  Sorry, I should have forwarded you that link.  Thanks for finding it.

**Comment by eltonjrv** [comment]
Thanks again, David!

One last question:
When is SMRTanalysis 3.0 going to be widely available for download?
Is this the only way I can have "bax2bam"?

Thanks,
Cheers,
Elton

2016-01-12 13:55 GMT-02:00 David Alexander <notifications@github.com>:

> Yes, that's right. Sorry, I should have forwarded you that link. Thanks
> for finding it.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/PacificBiosciences/GenomicConsensus/issues/40#issuecomment-170955605>
> .
>



-- 
Elton J. R. Vasconcelos
DVM, PhD

**Comment by dalexander** [comment]
I think it will be available early this spring, though I'm not sure the exact date

bax2bam may be made available on github sooner, we are working on it

**Comment by eltonjrv** [comment]
Ok, Great!

I'll be checking that out!
Congrats for your effort on heading the new version of smrtanalysis.

Best,
Elton

2016-01-12 14:08 GMT-02:00 David Alexander <notifications@github.com>:

> I think it will be available early this spring, though I'm not sure the
> exact date
>
> bax2bam may be made available on github sooner, we are working on it
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/PacificBiosciences/GenomicConsensus/issues/40#issuecomment-170959393>
> .
>



-- 
Elton J. R. Vasconcelos
DVM, PhD
