### ISSUE TITLE
Problem installing dependencies

### ISSUE THREAD

**Issue by isovic** [PacificBiosciences/GenomicConsensus#44]
Hi,

I was following the detailed installation instructions listed here:
https://github.com/PacificBiosciences/GenomicConsensus/blob/master/doc/HowToQuiver.rst
After reaching this step:
```pip install git+https://github.com/PacificBiosciences/ConsensusCore2```
the process failed with the following message (only the last part):
```
    [ 92%] Building CXX object CMakeFiles/pbconsensus.dir/src/Integrator.cpp.o
    Linking CXX static library /tmp/pip-m5nWv5-build/lib/libpbconsensus.a
    [ 92%] Built target pbconsensus
    [ 96%] Generating ConsensusCore2_wrap.cxx
    /tmp/pip-m5nWv5-build/include/pacbio/consensus/align/AlignConfig.h:61: Error: Syntax error in input(1).
    make[2]: *** [swig/ConsensusCore2_wrap.cxx] Error 1
    make[1]: *** [swig/CMakeFiles/_ConsensusCore2.dir/all] Error 2
    make: *** [all] Error 2
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-m5nWv5-build/setup.py", line 63, in <module>
        raise RuntimeError("failed to compile or link ConsensusCore2!")
    RuntimeError: failed to compile or link ConsensusCore2!

    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in /tmp/pip-m5nWv5-build
```

There are also many warnings about comparison between signed and unsigned integer expressions.

Do you know what might be causing this?

Best regards,
Ivan.

**Comment by dalexander** [comment]
Hi Ivan, `ConsensusCore2` is not required for quiver, it is used for our next-generation algorithm *arrow*, which isn't quite ready yet.

You want `ConsensusCore`---see if you can install that one.

**Comment by isovic** [comment]
Oh I see. I didn't realize that, both are on the list in "Step 2: Install PacBio libraries" (https://github.com/PacificBiosciences/GenomicConsensus/blob/master/doc/HowToQuiver.rst)
Thank you,
Best regards,
Ivan.

**Comment by dalexander** [comment]
You're right, I will have to fix that document.

**Comment by robsyme** [comment]
I tried replacing ConsensusCore2 with ConsensusCore, but it doesn't look to be packaged correctly?
```
$ sudo -H pip install git+https://github.com/PacificBiosciences/ConsensusCore
Collecting git+https://github.com/PacificBiosciences/ConsensusCore
  Cloning https://github.com/PacificBiosciences/ConsensusCore to /tmp/pip-qgLFJW-build
    Complete output from command python setup.py egg_info:
    WARNING: '' not a valid package name; please use only.-separated package names in setup.py
    running egg_info
    creating pip-egg-info/ConsensusCore.egg-info
    writing pip-egg-info/ConsensusCore.egg-info/PKG-INFO
    writing top-level names to pip-egg-info/ConsensusCore.egg-info/top_level.txt
    writing dependency_links to pip-egg-info/ConsensusCore.egg-info/dependency_links.txt
    writing manifest file 'pip-egg-info/ConsensusCore.egg-info/SOURCES.txt'
    warning: manifest_maker: standard file '-c' not found
    
    error: package directory 'build/Python' does not exist
    
    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in /tmp/pip-qgLFJW-build 
```

**Comment by dalexander** [comment]
I think you have to manually download and run setup.py for CC, we never got that working smoothly.  

I see you're a fan of nextflow, how is it working for you?

**Comment by robsyme** [comment]
Yup, picking the package up from /tmp and then manually installing works fine.

Big fan of Nextflow. Great balance between being easy to write/reuse and capturing complex data flow.
