### ISSUE TITLE
too many indices for array error 

### ISSUE THREAD

**Issue by chklopp** [PacificBiosciences/GenomicConsensus#66]
I try to quiver a medium size genome.
The cmp.h5 file has been create with pbalign using the --forQuiver option.

When I run the quiver command line hereunder I get an IndexError: too many indices for array

(VE-QUIVER)bash-4.1$ quiver -j16 -v m151216_140937_42263_c100841882550000001823167612311547_s1_p0_2.cmp.h5 -r p_ctg.fa -o test1.gff -o test1.fasta
[INFO] h5py version: 2.5.0
[INFO] hdf5 version: 1.8.5
[INFO] ConsensusCore version: 1.0.1
[INFO] Starting.
[INFO] Peeking at file /work/sigenae/Project_JavaFish.561/m151216_140937_42263_c100841882550000001823167612311547_s1_p0_2.cmp.h5
[INFO] Input data: numAlnHits=85817
[INFO] Loading reference
[INFO] Loaded 989 of 989 reference groups from /work/sigenae/Project_JavaFish.561/p_ctg.fa 
[INFO] Using Quiver parameters file /usr/local/bioinfo/src/Quiver/VE-QUIVER/lib/python2.7/site-packages/GenomicConsensus/quiver/resources/2014-09/GenomicConsensus/QuiverParameters.ini
[INFO] Using Quiver parameter set(s): P6-C4.AllQVsMergingByChannelModel
[INFO] Available CPUs: 64
[INFO] Requested workers: 16
[INFO] Parallel Mode: Process
[INFO] Launched compute slaves.
[INFO] Launched collector slave.
[INFO] Quiver operating on 000000F:50781-51005
[INFO] Quiver operating on 000000F:50995-51505
[INFO] Quiver operating on 000000F:51495-52005
[INFO] Quiver operating on 000000F:51995-52505
[INFO] Quiver operating on 000000F:52495-53005
[INFO] Quiver operating on 000000F:52995-53505
[INFO] Quiver operating on 000000F:53495-54005
[INFO] Quiver operating on 000000F:53995-54505
[INFO] Quiver operating on 000000F:54495-54916
[INFO] Quiver operating on 000000F:299514-300005
[INFO] Quiver operating on 000000F:299995-300505
[INFO] Quiver operating on 000000F:300495-301005
[INFO] Quiver operating on 000000F:300995-301505
[INFO] Quiver operating on 000000F:301495-302005
[INFO] Quiver operating on 000000F:301995-302180
[INFO] Quiver operating on 000000F:1044323-1044505
Process QuiverWorkerProcess-10:
Traceback (most recent call last):
  File "/usr/local/bioinfo/src/python/current/lib/python2.7/multiprocessing/process.py", line 258, in _bootstrap
    self.run()
  File "/usr/local/bioinfo/src/Quiver/VE-QUIVER/lib/python2.7/site-packages/GenomicConsensus/Worker.py", line 96, in run
    self._run()
  File "/usr/local/bioinfo/src/Quiver/VE-QUIVER/lib/python2.7/site-packages/GenomicConsensus/Worker.py", line 77, in _run
    result = self.onChunk(datum)
  File "/usr/local/bioinfo/src/Quiver/VE-QUIVER/lib/python2.7/site-packages/GenomicConsensus/quiver/quiver.py", line 196, in onChunk
    refContig, options.coverage, self.quiverConfig)
  File "/usr/local/bioinfo/src/Quiver/VE-QUIVER/lib/python2.7/site-packages/GenomicConsensus/quiver/quiver.py", line 118, in consensusAndVariantsForWindow
    siteCoverage = U.coverageInWindow(subWin, alns)
  File "/usr/local/bioinfo/src/Quiver/VE-QUIVER/lib/python2.7/site-packages/GenomicConsensus/quiver/utils.py", line 404, in coverageInWindow
    tStart = a[:,0]
IndexError: too many indices for array

NB. When I do the same on a small bacterial genome it works.
What can be the origin of the error?

Ch+

**Comment by dalexander** [comment]
Can you show `quiver --version` output please?

**Comment by chklopp** [comment]
(VE-QUIVER)bash-4.1$ quiver --version
  GenomicConsensus version: 1.1.0
  ConsensusCore version: 1.0.1
  h5py version: 2.5.0
  hdf5 version: 1.8.5

**Comment by dalexander** [comment]
you closed the issue, have you resolved it?

**Comment by chklopp** [comment]
Sorry

**Comment by chklopp** [comment]
The error comes from the comment/description in the header reference fasta file used for pbalign and quiver. When I keep only the identifier in the fasta header, line the error disappears. 
This means that somewhere in the process a piece of software could be changed in order to use only the identifier information from the fasta file even if a description exists.

**Comment by dalexander** [comment]
In 2.3, we used the full FASTA header as the identifier.  In 3.0, we have switched, everywhere, to using the first whitespace-delimited token as the identifier.  If you are using a github-built quiver with a pbalign from 2.3 SMRTanalysis, I wonder if that could explain the problem.

Regardless, we should give a more informative error message in instances like this.  Would you mind emailing me at dalexander@pacificbiosciences.com and we can discuss how I could look at your data files?

**Comment by chklopp** [comment]
My mail to dalexander@pacificbiosciences.com was rejected : 554 rejected due to spam content

I'm polishing a Falcon assembly file.

grep '^>' 2-asm-falcon/p_ctg.fa | head
>000000F 000541970:E~000859516:B~001394547:B~002655973:E ctg_linear 16487608 66962654
>000001F 001993323:E~002706704:B~001025546:B~003102591:B ctg_linear 16174135 68407008
>000002F 003267448:B~000738095:B~001189163:B~000347351:B ctg_linear 15983599 66813731
>000003F 000578921:E~003134426:B~000947936:E~001443370:E ctg_linear 14395644 59744339
>000004F 002723321:E~001061502:E~000670646:B~002953054:E ctg_linear 14031383 57505129
>000005F 001596470:B~000721113:B~001020308:B~001703507:B ctg_linear 12890172 53589691
>000006F 000478247:E~002145280:B~001607506:B~002337951:E ctg_linear 11843214 50639019
>000007F 000599714:B~002617806:E~003352855:B~001427624:B ctg_linear 10948972 47558794
>000008F 002343134:B~001873789:E~000652530:B~002677798:E ctg_linear 10893988 43175431
>000009F 000665698:E~002741003:B~002645735:B~003297772:B ctg_linear 10708592 41885391

**Comment by dalexander** [comment]
OK, just send me an email with your address
