### ISSUE TITLE
Quiver virtual environment

### ISSUE THREAD

**Issue by JeanQin** [PacificBiosciences/GenomicConsensus#70]
We're told to install quiver from github in order to use .fofn for multiple bam files to polish falcon contigs.

Your online document suggests to install in separate machine from smrtanalysis to prevent from corrupting the present smrtanalysis installation. We manage different package installation by environment modules on the same system. Could you let us know what're the some environments for quiver need to be different from the rest of the smrtanalysis package so installation of quiver won't corrupt smrtanalysis? 

Here's your online document we're trying to follow for installation.

Thanks,
 Jean

**Comment by dalexander** [comment]
If you make sure that your SMRTanalysis is installed "read only", I think you won't have problems.

I don't honestly know whether this is the default behavior---I certainly hope it is.

Installing GenomicConsensus entails installing a host of dependencies---`ConsensusCore`, `pbcore` are the main ones, which in turn require `numpy`, etc.

**Comment by JeanQin** [comment]
Thanks, David for your suggestion. We manage different packages separately by environment modules such that when we load one package, all its dependencies will be loaded. Is it sufficient to isolate quiver from smrtanalysis? Do you still recommend to make smrtanalysis read-only?  Is the "read-only" needed only during quiver installation or also needed when running quiver? Can we run some smrtanalysis tools after quiver installed?  When you said to make sure your SMRTanalysis is installed "read only", do you mean to change smrtanalysis directory permission to read-only? Sorry for so many questions. We're still using smrtanalysis so we want to be caution to install quiver to make sure they're not interfere each other.

We'd like to know what're needed to include in the quiver installation package besides the dependencies listed on your website? https://github.com/PacificBiosciences/GenomicConsensus/blob/master/doc/HowToQuiver.rst

Thanks,
Jean

**Comment by dalexander** [comment]
I do not advise attempting to "mix" the virtualenv and your SMRTanalysis install in any manner.  Just leave your SA install alone and install a totally separate virtualenv where you install GenomicConsensus and all its dependencies.  You then can only run in one environment at a time, so you will have to update your script to invoke the correct environment before calling a tool.

**Comment by JeanQin** [comment]
Thanks, David for your advise. We'll give it a try. Keep our fingers crossed.
