### ISSUE TITLE
Quiver troubleshooting

### ISSUE THREAD

**Issue by arthurmelobio** [PacificBiosciences/GenomicConsensus#79]
Hi Quiver Team, 

We're running Falcon for a plant genome assembly using 116 SMRT cells on CyVerse Discovery Environment from iPlant.
We also have the quiver installed on CyVerse for pos assebly polishing but I need to create the app (GUI interface) for users.

Once the users cannot control the memory issues on CyVerse the only command line options are the inputs (alignments outputs and reference) and the outputs (variants and consensus)? I mean, I need to choice just one -o flag (variants.gff or consensus.fasta or consensus.fastq) or I can set the three -o flags together?

The command line needs to be:
$ quiver aligned_reads -r reference.fasta -o variants.gff -o consensus.fasta -o consensus.fastq

I missed something?

Also, the variants called are required like input or output? Here, on GitHub it seems a output, but on SMRT® Pipe Reference Guide (begin of page 22) it appers both like input and output. 

Finaly, what is the conceptual difference between the pre-assembly error correction step done by Daligner/Falcon and this pos-assembly polishing procedure?

Thank you so much for any help.

Best,
Arthur

**Comment by dalexander** [comment]
Hi there, you can do  `-o variants.gff` or `-o variants.gff -o consensus.fasta` for example---each `-o` flag specifies a different output file, and there can be multiple.

**Comment by dalexander** [comment]
The SMRTpipe document you refer to documents the SMRTpipe resequencing workflow, not the quiver tool itself.   The SMRTpipe resequencing workflow encompasses the call to quiver and then additional steps.  In particular, an `alignment_summary.gff` file (*not* a variants.gff file) is updated (used as input and output) to record variant call summary information across the genome.

The pre-assembly correction algorithm is a fast heuristic algorithm that is totally unrelated to the statistical algorithm in quiver.  You can read about these in the 2013 paper on HGAP.
