### ISSUE TITLE
what file formats for arrow?

### ISSUE THREAD

**Issue by StefanoLonardi** [PacificBiosciences/GenomicConsensus#91]
Hello,
I want to try arrow for my resequencing (polishing) step for my denovo assembly. I have had success running quiver, but when I use the same files with arrow I get an error.

Here is my pipeline:
1) align pacbio reads to ref assembly using `pbalign --forQuiver reads.bax.h5 ref.fasta out.cmp.h5` 
2) merge all the out.cmp.h5 using `cmph5tools.py merge` 
3) sort `cmph5tools.py sort` and `h5repack -f GZIP=1` to produce a large `allpacked.cmp.h5` file

When I run `variantCaller -j 20 --algorithm=arrow allpacked.cmp.h5 -r ref.fasta -o variants.gff -o consensus.fasta -o consensus.fastq` I get the error `Arrow does not support CmpH5 files`. If I specify `--algorithm=quiver`, it works. What file formats does arrow require? I could not find this information anywhere in the documentation. By snooping in the source files, I also found the option `--algorithm=best`.

**Comment by evolvedmicrobe** [comment]
Arrow only works with the BAM file format, if you are using P6-C4 data it will work about as well as Quiver, so there is little value in switching algorithms (Unless you are looking to try something more specific, in which case please let us know!).

Running bax2bam to covert the initial bax files to BAM and then running your pipeline would likely accomplish your goal though.
