### ISSUE TITLE
failed to run quiver

### ISSUE THREAD

**Issue by wisekh6** [PacificBiosciences/GenomicConsensus#92]
Hello,
After installing SMRT-analysis, I tried to run 'quiver', but it caused an error related to missing python script:

```
[hkim6@cnode337 bin]$ ./quiver
Traceback (most recent call last):
  File "/scratch/bcb/hkim6/IACS2Verhaak/pipeline/PacBio/smrtanalysis/current/analysis/bin/variantCaller.py", line 3, in <module>
    from GenomicConsensus.main import main
ImportError: No module named GenomicConsensus.main
```

Would you let me know how to work around this error?

thank you,

**Comment by afif-elghraoui** [comment]
Cross-posted at https://github.com/PacificBiosciences/SMRT-Analysis/issues/275
This isn't really an issue with quiver.

**Comment by dalexander** [comment]
thanks Afif.
