### ISSUE TITLE
default max coverage parameter appears to be too low

### ISSUE THREAD

**Issue by afif-elghraoui** [PacificBiosciences/GenomicConsensus#93]
It's pretty common these days for microbial sequencing runs to generate >100x coverage. Is there an algorithmic reason to even have a maximum coverage, or is this to prevent computational resource requirements from uncontrollably ballooning? I noticed some suboptimal calls using 2 SMRTCells vs 1 SMRTCell, and those were resolved when I set maximum coverage to 1000.

**Comment by dalexander** [comment]
The reason for a limit was amplicon sequencing, where people would have small windows of the genome with maybe 10000x coverage... so yes, the purpose was to avoid computational excesses.

But you may be right that 100x is too low.  I chose 100x because it seemed to represent a point after the "plateau" I observed on all the runs I looked at at a certain time.  But maybe 250 would be more conservative?

Could you try 250x?

**Comment by afif-elghraoui** [comment]
This sample with both SMRTCells has about 220x average coverage, but I tried 250 like you said, and I do get the same results as I did with 1000.

The suboptimal calls I was talking about with 100x are [single-base indels in short homopolymers](https://github.com/PacificBiosciences/GenomicConsensus/blob/master/doc/FAQ.rst#what-are-the-residual-errors-after-applying-quiver) with respect to each of the two single-SMRTCell polished assemblies. I manually checked one of the calls in the alignment of the combined data and found better support for the call in the single-SMRTCell assemblies. That call wasn't made by Quiver on the combined data until I raised the maximum coverage.

**Comment by dalexander** [comment]
Very interesting.  For how many sites did you observe this?  And, can you tell me a bit about the size and nature of the genome?

**Comment by afif-elghraoui** [comment]
They're a total of 9 sites. 5 were made in each single run, 2 were only in one, and another 2 were only in the other. None of them appeared in the combined run with the default max coverage. After raising it, I see 7 of the 9. The remaining 2 were among those that only appeared in one of the single runs.

The one I'm talking about that I manually checked was among the 5 that both individual runs called. This genome is for a Mycobacterium tuberculosis strain, 4.4Mbp.

I noticed some ambiguity in the next-to-last sentence of my last post; I'm going to edit it now.

**Comment by afif-elghraoui** [comment]
To add on to the "nature of the genome" part, it has a family of genes (PE/PPE) that are repetitive and GC-rich. Overall GC-content is about 65%

**Comment by dalexander** [comment]
We are going to leave the default as is for now since it works reliably on our in-house samples and is computationally favorable.  You are always welcome to choose a higher value.

**Comment by afif-elghraoui** [comment]
I don't think there was a way to set this parameter in the SMRTAnalysis 2.3 workflow XML files.

In any case, people expect all their reads to be counted when they call consensus and they expect defaults to meet their expectations of the common use case. See, for example, https://twitter.com/MicroWavesSci/status/767799186943246337. I personally don't mind what happened here because I noticed it (after two or three scans through the options list) and, like you said, I can change it.
